name: emsim
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pytorch-cuda=11.8
  - pytorch::pytorch
  - pip
  - h5py
  - cython
  - matplotlib
  - numpy
  - pandas
  - pillow
  - tensorboard
  - tensorboardx
  - lightning
  - torchmetrics
  - pycocotools
  - hydra-core
  - yaml
  - scipy
  - seaborn
  - torchvision
  - transformers
  - huggingface_hub
  - datasets
  - timm
  - ipython
  - notebook
  - ipympl
  - sparse
  - fire
  - torchquad
  - deprecation
  - pip:
    - stempy
    - cumm-cu118
    - spconv-cu118