name: emsim
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.11 # highest supported python version for spconv
  - pytorch-cuda=12.4  # required by spconv
  # - cuda=12.1
  - pytorch::pytorch
  - sparse=0.15 # conda wants to install 0.3 if you let it
  # - thrust # for MinkowskiEngine
  - lightning
  - tensorboard
  - tensorboardx
  - torchmetrics
  - pycocotools
  - hydra-core
  - torchvision
  - transformers
  - timm
  # - torchquad
  # - pandas
  # - pillow
  - pip
  - h5py
  - cython
  - matplotlib
  # - seaborn
  - numpy
  - yaml
  - pynvml
  - scipy
  # - huggingface_hub
  # - datasets
  - ipython
  - notebook
  - ipympl
  - termcolor
  - portalocker
  - sympy
  - fire
  - ninja
  - lark
  - pytest
  - deprecation
  - pip:
    - stempy
    # - cumm-cu120
    # - spconv-cu120