name: emsim
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - h5py
  - cython
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pytorch::pytorch
  - scipy
  - seaborn
  - torchvision
  - transformers
  - huggingface_hub
  - datasets
  - timm
  - ipython
  - notebook
  - ipympl
  - sparse
  - fire
  - torchquad
  - deprecation
  - pip:
    - stempy
    - pylandau