defaults:
  - base_config
  - model: default
  - dataset: default
  - training: default
  - _self_

spatial_dimension: 2

seed: 1234
device: "cuda"

debug: false

ddp:
  nodes: 2
  devices: 2
  find_unused_parameters: ${debug}
  detect_anomaly: ${debug}