use_denoising: false
embed_dim: ${model.transformer.d_model}
max_electrons_per_image: 400
max_total_denoising_queries: 1200
position_noise_variance: 1.0
mask_main_queries_from_denoising: false
pos_neg_queries_share_embedding: false
denoising_loss_weight: 1.0